site_name: Documentation Library
site_url: https://docs.cumulus26.com

theme:
  name: material
  logo: assets/images/c26square.png
  favicon: assets/images/favicon.webp
  features:
    - navigation.tracking
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
  palette:
    primary: custom
    accent: blue
  social:
    - icon: material/youtube
      link: https://www.youtube.com/@Cumulus26  
    - icon: material/linkedin
      link: https://www.linkedin.com/company/cumulus26

extra_css:
  - assets/css/style.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Docs Home: index.md
  - Main site: https://cumulus26.com
  - Get Started: get-started.md
  - Glossary: glossary.md
  - FAQ: faq.md
  - Contact Us: https://cumulus26.com/contact-us
  

plugins:
  - meta

copyright: Copyright &copy; 2025 Cumulus26

